# Generated by Django 5.2.17 on 2026-09-20 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0003_locationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('document', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_versions', to='accounts.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='policies.policy')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_policy_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DevicePolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_policy_assignments', to=settings.AUTH_USER_MODEL)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignment', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_policy_assignments', to='accounts.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_assignments', to='policies.policy')),
                ('pinned_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinned_assignments', to='policies.policyversion')),
            ],
            options={
                'verbose_name': 'device policy assignment',
                'verbose_name_plural': 'device policy assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'name'), name='uniq_active_policy_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version_number'), name='uniq_policy_version_number'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('policy',), name='uniq_one_published_policy_version'),
        ),
    ]
