# Generated by Django 5.2.17 on 2026-09-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_locationrecord'),
        ('policies', '0001_policy_domain_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='applied_policy_version_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='policies.policyversion'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='policy_ack_client_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='policy_ack_result',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='policy_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='policy_last_error',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
